name: content-search-ai

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11

  # Core
  - pip
  - setuptools<81
  - wheel

  - numpy=1.26.4
  - pandas
  - matplotlib
  - tqdm
  - pillow
  - requests
  - ffmpeg
  - librosa
  - watchdog
  - sqlite

  # PyTorch CPU
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - cpuonly

  # Vector search
  - faiss-cpu

  # Jupyter
  - ipykernel
  - jupyterlab

  - pip:
      - numpy<2
      - soundfile
      - pymupdf
      - openai-whisper
      - faster-whisper>=1.0.3
      - sentence-transformers==3.0.1
      - transformers==4.45.2
      - huggingface-hub<1.0
      - regex
      - ftfy
      - clip-anytorch==2.6.0
      - tiktoken
      - gdown
      - python-multipart
      - opencv-python==4.10.0.84
      - pygame
      - streamlit>=1.38.0
